FROM node:20-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install --no-cache && npm cache clean --force

COPY . .

EXPOSE 3000

CMD ["npm", "start"]